language: node_js
node_js:
- '4'
- '6'
script: travis_retry grunt build && npm run protractor-sauce
before_script:
- npm install -g bower grunt-cli
- bower install
env:
  global:
  - secure: AsoJDUsQ/X+zsB76UuBkYeDEnEIAgbtBg+n6wzd6l4fSDGdPfLQaVfRgW9JR0++nwrG4/WSd+DfdH/jJ1izyHX4Ap+Q6KxRNEnGZwAsIWeytshs2rwIrW7kFahPG8t2pgN/NII8yRPJIlyp2SCpUh1dRMhGcwsy4r4lsWSriRV8=
  - secure: vf0ZwRFA96Vfa6SgUXc0uvbSmFdX5LfrXYkickaTJ5ln8oIsfdzxv7+Fu80f5WBbYDynRrrBPADubEVl8YgsshlSrha7UYG2ybK1j1RbtN2CVUHL8nEr49hTwxN9SoNCJMFgxYJ0BDTwelvSJHuUBoiqphjVHaUIn0iREk96eIU=
