language: node_js
node_js:
- '4'
- '6'
script: travis_retry grunt build && npm run protractor-sauce
before_script:
- npm install -g bower grunt-cli
- bower install
env:
  global:
  - secure: AsoJDUsQ/X+zsB76UuBkYeDEnEIAgbtBg+n6wzd6l4fSDGdPfLQaVfRgW9JR0++nwrG4/WSd+DfdH/jJ1izyHX4Ap+Q6KxRNEnGZwAsIWeytshs2rwIrW7kFahPG8t2pgN/NII8yRPJIlyp2SCpUh1dRMhGcwsy4r4lsWSriRV8=
  - secure: vf0ZwRFA96Vfa6SgUXc0uvbSmFdX5LfrXYkickaTJ5ln8oIsfdzxv7+Fu80f5WBbYDynRrrBPADubEVl8YgsshlSrha7UYG2ybK1j1RbtN2CVUHL8nEr49hTwxN9SoNCJMFgxYJ0BDTwelvSJHuUBoiqphjVHaUIn0iREk96eIU=
  - secure: WrLnXlTHBHXK8IJzQsIQ0KWlXjAZi7Ns0pRbI1xgZ6PNogFw+qwdvI9fnNP/jbc9SkmQgESJep2NtDfeRFZogUEcr9+0oMndeEf1tIY98aQhZWIj5MuKAXmSUkESrIx2Dqj50k7VTO9ESw+KIPaMTsjyE2fCmcykp+gxLnle37Q=
  - secure: jrc0vyKqReqyvdFkStajRNWP1uzNvCtR/rmWN4plUPyzd5a7rRvs2pnJWpVQ9xS69n/muD9uJiHAV9v/jjzRvHS2UOn8HlFPjPda9lksEy641IiOnEwG2G8FR9YBJnyus4YX/vFr12wFBV4Rs6wSRkco2malP8KOFHIJPvs4mR0=
